### ISSUE TITLE
Client no work

### ISSUE THREAD

**Issue by njgingrich** [njgingrich/aocrunner#14]
```sh
➜ aocrunner submit 2
Submitting part 2 solution.
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'ApiClient')
    if (!this.#canSubmit()) {
              ^
    at submit (https://jsr.io/@njgingrich/aocrunner/0.1.15/src/api/client.ts:180:15)
    at submitDay (https://jsr.io/@njgingrich/aocrunner/0.1.15/src/actions/submit.ts:57:23)
    at submit (https://jsr.io/@njgingrich/aocrunner/0.1.15/src/cli/submit.ts:21:10)
    at async main (https://jsr.io/@njgingrich/aocrunner/0.1.15/src/cli/index.ts:31:15)
```

**Comment by njgingrich** [comment]
Fixed in commit.
