### ISSUE TITLE
Handle 404 errors

### ISSUE THREAD

**Issue by njgingrich** [njgingrich/aocrunner#4]
```sh
➜ deno task day 1
Task day aocrunner day "1"
Unknown error: {
  type: "UNKNOWN",
  error: Error: Failed to fetch https://adventofcode.com/0/day/1/input: Not Found
    at ApiClient.getInput (https://jsr.io/@njgingrich/aocrunner/0.1.12/src/api/client.ts:154:15)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async day (https://jsr.io/@njgingrich/aocrunner/0.1.12/src/cli/day.ts:44:22)
    at async main (https://jsr.io/@njgingrich/aocrunner/0.1.12/src/cli/index.ts:34:15)
}
```

**Comment by njgingrich** [comment]
Completed in https://github.com/njgingrich/aocrunner/commit/e07512d5a8e6d2fc538be241374aeae2f6395cb7
